services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: tracking_db
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pedidos-net
    volumes:
      - mysql-data:/var/lib/mysql

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      # Sobrescribimos la URL de la base de datos para que apunte al contenedor mysql-db en lugar de localhost
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/tracking_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpass
    depends_on:
      mysql-db:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./auth-service
          target: /app/src
        - action: rebuild
          path: ./auth-service/pom.xml
    networks:
      - pedidos-net

  # ── SERVICIOS PENDIENTES DE IMPLEMENTACIÓN ──
  # Descomentaremos estos servicios a medida que los vayamos implementando

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      # Sobrescribimos la URL de la base de datos para que apunte al contenedor mysql-db en lugar de localhost
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/tracking_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpass
    depends_on:
      mysql-db:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./user-service
          target: /app/src
        - action: rebuild
          path: ./user-service/pom.xml
    networks:
      - pedidos-net

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8083:8083"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      # Sobrescribimos la URL de la base de datos para que apunte al contenedor mysql-db en lugar de localhost
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/tracking_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpass
    develop:
      watch:
        - action: sync+restart
          path: ./order-service
          target: /app/src
        - action: rebuild
          path: ./order-service/pom.xml
    networks:
      - pedidos-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - order-service
      - user-service
    develop:
      watch:
        - action: sync+restart
          path: ./api-gateway
          target: /app/src
        - action: rebuild
          path: ./api-gateway/pom.xml
    networks:
      - pedidos-net

networks:
  pedidos-net:
    driver: bridge

volumes:
  mysql-data:
